### ISSUE TITLE
No module named 'tensorflow'

### ISSUE THREAD

**Issue by AndresPrada** [alexeygrigorev/tensorflow-protobuf#1]
Thanks for the proto files. They are very useful. However, I'm getting one error when using these files. When I run them without tf installed, I get the following error:

``
File "/home/andres/Documents/GitHub/podolino_tf2/src/TensorHelper.py", line 1, in <module>
    from .protos.tensorflow_proto.core.framework import tensor_pb2, tensor_shape_pb2, types_pb2
  File "/home/andres/Documents/GitHub/podolino_tf2/src/protos/tensorflow_proto/core/framework/tensor_pb2.py", line 14, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
ModuleNotFoundError: No module named 'tensorflow'
``

Is there a way to overcome this issue? Or do I need to edit the proto files directly?

**Comment by alexeygrigorev** [comment]
Perhaps it was too naive from my side to assume that simple ranaming of the directories would help - and also it shows that having tests is sometimes useful =)

The example needs to be changed to 

```
from tensorflow.core.framework import tensor_pb2, tensor_shape_pb2, types_pb2
from tensorflow_serving.apis import prediction_service_pb2_grpc
from tensorflow_serving.apis import predict_pb2
```

and the directories should be renamed (remove `_proto`)

Then it'll work

**Comment by alexeygrigorev** [comment]
okay now I renamed everything back - this should hopefully work.
